---
root_domain: "{{ enclave }}.{{ base_domain }}"
domain_delimiter: "-"
namespace: "{{ enclave }}"
source_secret_name: "{{ base_domain }}-tls"
k8s_api_retry_number_max_limit: 10
k8s_api_retry_delay_sec: 3
helm_local_src: false
model_docker_protocol: https
model_resources_cpu: 256m
model_resources_mem: 256Mi