---
dashboard:
  version: "1.10.1"
  insecure: true
source_secret_name: "{{ base_domain }}-tls"
monitoring_prometheus_operator_crd_url: "https://raw.githubusercontent.com/coreos/prometheus-operator/v0.29.0/example/prometheus-operator-crd"
monitoring_values_file: "{{ tmp_dir }}/monitoring.{{ cluster_name }}.yml"
# Cluster logs
kube_fluentd:
  kube_s3_bucket_name: epm-legion-data-dev-logs
  kube_s3_bucket_region: us-east-2
  # kube_s3_bucket_prefix: cluster_logs
  system_s3_bucket_name: epm-legion-data-dev-logs
  system_s3_bucket_region: us-east-2
  # system_s3_bucket_prefix: cluster_logs
  services_s3_bucket_name: epm-legion-data-dev-logs
  services_s3_bucket_region: us-east-2
  # services_s3_bucket_prefix: cluster_logs