keycloak:
  image:
    repository: ${keycloak_image_repository}
    tag: ${keycloak_image_tag}

  username: ${keycloak_admin_user}
  password: ${keycloak_admin_pass}

  ingress:
    enabled: true
    path: /
    annotations: {}
    hosts:
      - "keycloak.${cluster_name}.${root_domain}"
    tls:
      - hosts:
          - "keycloak.${cluster_name}.${root_domain}"
        secretName: "${cluster_name}-tls"

  ## Persistence configuration (postgresql in this case)
  persistence:
    dbVendor: postgres
    deployPostgres: true
    dbName: keycloak
    dbHost: mykeycloak
    dbPort: 5432
    dbUser: "${keycloak_db_user}"
    dbPassword: "${keycloak_db_pass}"

postgresql:
  ### PostgreSQL User to create.
  ##
  postgresUser: "${keycloak_pg_user}"

  ## PostgreSQL Password for the new user.
  ## If not set, a random 10 characters password will be used.
  ##
  postgresPassword: "${keycloak_pg_pass}"