replicaCount: "${dex_replicas}"

issuer: "https://dex.${cluster_name}.${root_domain}"

service:
  externalIPs: "${dex_external_ip}"

connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: "${dex_github_clientid}"
      clientSecret: "${dex_github_clientSecret}"
      redirectURI: https://dex.${cluster_name}.${root_domain}/callback # DEX callback URL
      orgs:
      - name: "${github_org_name}"

staticClients:
  - id: "${dex_client_id}"
    secret: "${dex_client_secret}"
    redirectURIs:
    - "https://auth.${cluster_name}.${root_domain}/oauth2/callback"
    - "https://auth.${cluster_name}.${root_domain}/callback/${cluster_name}"
    name: "${cluster_name} Cluster"

staticPasswords:
  - email: "${dex_static_user_email}"
    password: "${dex_static_user_pass}"
    hash: "${dex_static_user_hash}"  # bcrypt hash of the password string
    username: "${dex_static_user_name}" 
    userID: "${dex_static_user_id}"

enablePasswordDB: false

tls_secret: "${cluster_name}-tls"
