config:
  provider: oidc
  redirect_url: "https://auth.${cluster_name}.${root_domain}/oauth2/callback"
  oidc_issuer_url: "https://keycloak.${cluster_name}.${root_domain}/auth/realms/master"
  whitelist_domain: ".${cluster_name}.${root_domain}"
  cookie_domain: ".${cluster_name}.${root_domain}"
  cookie_secure: true
  cookie_expire: "${dex_cookie_expire}"
  email_domains: "*"
  github-org: "legion-auth-gcp"
  set_authorization_header: true
  skip_provider_button: true
  scope: openid profile email offline_access groups
  http_address: 0.0.0.0:4180
  client_secret: "${keycloak_client_secret}"
  client_id: "${keycloak_client_id}"
ingress:
  path: /oauth2
  enabled: true
  hosts:
    - "auth.${cluster_name}.${root_domain}"
  tls:
  - secretName: "${cluster_name}-tls"
    hosts:
    - "auth.${cluster_name}.${root_domain}"
