config:
  provider: iodc
  redirect_url: "https://auth.${cluster_name}.${root_domain}/oauth2/callback"
  oidc_issuer_url: "https://dex.${cluster_name}.${root_domain}"
  whitelist_domain: ".${cluster_name}.${root_domain}"
  cookie_domain: ".${cluster_name}.${root_domain}"
  cookie_secure: true
  cookie_expire: "${dex_cookie_expire}"
  email_domains: "*"
  set_authorization_header: true
  skip_provider_button: true
  scope: openid profile email offline_access groups
  http_address: 0.0.0.0:4180
  client_secret: "${dex_client_secret}"
  client_id: "${dex_client_id}"

ingress:
  path: /oauth2
  enabled: true
  hosts:
    - "auth.${cluster_name}.${root_domain}"
  tls:
  - secretName: "${cluster_name}-tls"
    hosts:
    - "auth.${cluster_name}.${root_domain}"

image:
  repository: "${docker_repo}/k8s-oauth2-proxy"
  tag: "${legion_infra_version}"
