---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: {{ template "k8s-gke-service-account-assigner.fullname" . }}
    rules:
      - apiGroups: [""]
        resources: ["namespaces","pods"]
        verbs: ["get","watch","list"]
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: {{ template "k8s-gke-service-account-assigner.fullname" . }}
    subjects:
    - kind: ServiceAccount
      name: {{ template "k8s-gke-service-account-assigner.serviceAccountName" . }}
      namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: {{ template "k8s-gke-service-account-assigner.fullname" . }}
      apiGroup: rbac.authorization.k8s.io
kind: List
---
